general.live_config_reload = true

[colors]

draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x666666"
blue = "0x0000ff"
cyan = "0x00e5e5"
green = "0x00d900"
magenta = "0x711c91"
red = "0xe50000"
white = "0xe5e5e5"
yellow = "0xe5e500"

[colors.normal]
black = "0x000000"
blue = "0x0000b2"
cyan = "0x00a6b2"
green = "0x00a600"
magenta = "0x711c91"
red = "0x990000"
white = "0xbfbfbf"
yellow = "0x999900"

[colors.primary]
background = "0x000000"
foreground = "0xb6b6b6"

[cursor]
style = "Underline"

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.bold]
family = "FiraCode Nerd Font Mono"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"

[font.italic]
family = "FiraCode Nerd Font Mono"

[font.normal]
family = "FiraCode Nerd Font Mono"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"
decorations_theme_variant = "Dark"
dynamic_padding = true
opacity = 0.35
title = "BLUcybrB14de@BattleGround"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 100
lines = 30
