
[window]
decorations = "Full"
opacity = 0.8
dynamic_title = true
dimensions = { columns = 115, lines = 30 }
padding = { x = 15, y = 15 }

[font]
size = 12.0
normal = { family = "Fira Code", style = "Regular" }
bold = { family = "Fira Code", style = "Bold" }
italic = { family = "Fira Code", style = "Italic" }
bold_italic = { family = "Fira Code", style = "Bold Italic" }

[cursor]
style = { shape = "Block", blinking = "Always" }

[selection]
save_to_clipboard = true

[general]
import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/alacritty_themes/catppuccin-latte.toml"
  # "~/.config/alacritty/alacritty_themes/catppuccin-frappe.toml"
  # "~/.config/alacritty/alacritty_themes/catppuccin-macchiato.toml"
  # "~/.config/alacritty/alacritty_themes/catppuccin-mocha.toml"
  # "~/.config/alacritty/alacritty_themes/rose-pine.toml"
  # "~/.config/alacritty/alacritty_themes/tokyo-night-storm.toml"
  # "~/.config/alacritty/alacritty_themes/rose-pine-dawn.toml"
  # "~/.config/alacritty/tokyonight_moon.toml"
  # "~/.config/alacritty/alacritty_themes/cyberpunk-neon.toml"
   "~/.config/alacritty/alacritty_themes/rose-pine-moon.toml"
]

[terminal]

[terminal.shell]
program = "/usr/bin/fish"
